image: ubuntu:18.04

tasks:
  - name: Dependencies
  - before: sudo apt update
  - init: sudo apt install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig ccache

  - name: RepoInit
  - before: mkdir -p ~/bin && curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
  - init: repo init -u https://android.googlesource.com/platform/manifest -c --submodules --depth=1
  - command: repo sync -j$(nproc)