image: ubuntu:18.04

tasks:
  - name: Dependencies
  - init: bash '/workspace/android_aosp_gitpod/gp.sh -d'

  - name: RepoInit
  - init: bash '/workspace/android_aosp_gitpod/gp.sh -r'
  - command: bash '/workspace/android_aosp_gitpod/gp.sh -s'
